modLoader="javafml"

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All Rights Reserved"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]]

modId="sculkatrophy" 
version="${file.jarVersion}"
displayName="Sculk Atrophy"
logoFile="sculkatrophy.png"
credits="Thanks to the Forge Discord"
authors="dragoni7" 
description='''
adds a simple effect to make traversing the Deep Dark more difficult
'''
[[dependencies.sculkatrophy]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.forge]]
    modId = "forge"
    mandatory = true
    versionRange = "[41.0.45,)"
    ordering = "NONE"
    side = "BOTH"

